### ISSUE TITLE
Simple model generates incorrect SQL query

### ISSUE THREAD

**Issue by Dooskington** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#44]
Hey.

Found a little bug today. If you have a very simple model such as this:

```
public class MyModel
{
    /// <summary>
    /// The Model Id and primary key.
    /// </summary>
    public int Id { get; set; }
}
```

Note that the Id field in this example is an auto-increment field.
If you try to create one, and save it in your database:

```
var model = new MyModel();
context.MyModels.Add(model);
context.SaveChanges();
```

You will get a `Microsoft.EntityFrameworkCore.DbUpdateException` exception, `An error occurred while updating the entries. See the inner exception for details.`

The referenced inner exception tells us:

```
`You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near
'DEFAULT VALUES;
SELECT `Id`
FROM `Conversation`
WHERE ROW_COUNT() = 1
AND `'
```

Here is the stacktrace of said exception:
```
Source=SapientGuardian.MySql.Data
       StackTrace:
            at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
            at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
            at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
            at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
            at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
            at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, String executeMethod, IReadOnlyDictionary`2 parameterValues, Boolean closeConnection)
            at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
            at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
```

Adding another field to the model fixes this error, showing that the error only happens with the simplest form of a model.

```
public class MyModel
{
    /// <summary>
    /// The Model Id and primary key.
    /// </summary>
    public int Id { get; set; }

    public string Test { get; set; } // There is now another value, so the query will work just fine.
}
```

We believe that the error is caused because, since the only field in the model is an auto-increment field, there is no value to be inserted. However, the part of the query that takes a value is still generated. When SQL interprets an empty value, it breaks.

**Comment by SapientGuardian** [comment]
I was able to reproduce this. I'm not 100% sure, but I think it's an upstream bug in EF, specifically this function: https://github.com/aspnet/EntityFramework/blob/master/src/Microsoft.EntityFrameworkCore.Relational/Update/UpdateSqlGenerator.cs#L321

If this bug is actually causing you grief, I'd suggest raising an issue in their repo.

**Comment by SapientGuardian** [comment]
Fixed by @TyrenDe (thanks!)

**Comment by TyrenDe** [comment]
I tested this locally, but there weren't tests to run in the project. Can you please confirm it fixed it for you too?

**Comment by SapientGuardian** [comment]
Yes, it fixed it for me.
