### ISSUE TITLE
is renaming index supported?

### ISSUE THREAD

**Issue by iemam** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#46]
it seems that rename index is not supported?

```
System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(RenameIndexOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(MigrationOperation operation, IModel model, MigrationCommandListBuilder builder)
   at Microsoft.EntityFrameworkCore.Migrations.MigrationsSqlGenerator.Generate(IReadOnlyList`1 operations, IModel model)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.GenerateUpSql(Migration migration)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The method or operation is not implemented.
```

**Comment by SapientGuardian** [comment]
I think you've answered your own question. Pull requests are welcomed!
