### ISSUE TITLE
Exception when trying to update-database

### ISSUE THREAD

**Issue by GuerrillaCoder** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#6]
I ran update-database but this exception comes up in the package manager console:

```
PM> update-database
System.ArgumentException: KeywordNotSupported Parameter name: trusted_connection
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.GetOption(String key)
    at MySql.Data.MySqlClient.MySqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at MySql.Data.MySqlClient.MySqlConnectionStringBuilder..ctor(String connStr)
    at MySql.Data.MySqlClient.MySqlConnection.set_ConnectionString(String value)
    at MySQL.Data.Entity.MySQLRelationalConnection.CreateDbConnection() 
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration) 
    at Microsoft.EntityFrameworkCore.Design.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType) 
   at Microsoft.EntityFrameworkCore.Tools.Cli.DatabaseUpdateCommand.<>c__DisplayClass0_0.<Configure>b__0()
    at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
    at Microsoft.EntityFrameworkCore.Tools.Cli.Program.Main(String[] args) 
 KeywordNotSupported 
Parameter name: trusted_connection 
```

Here is my C#

``` c#
var connection = "server = 192.168.0.15; user id = myuser; persistsecurityinfo = True; database = my_db";
services.AddDbContext<LeadContext>(options => options.UseMySQL(connection));
```

Any ideas what I did wrong?  I am guessing it is the connection string, I just copied that directly out of the server browser properties.

**Comment by GuerrillaCoder** [comment]
I hadn't rebuilt project so it was using the old connection string
